/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as FaqsRouteImport } from './routes/faqs'
import { Route as FeeScheduleRouteImport } from './routes/fee-schedule'
import { Route as MeetTheFounderRouteImport } from './routes/meet-the-founder'
import { Route as SolutionsRouteImport } from './routes/solutions'
import { Route as TheAcsApproachRouteImport } from './routes/the-acs-approach'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqsRoute = FaqsRouteImport.update({
  id: '/faqs',
  path: '/faqs',
  getParentRoute: () => rootRouteImport,
} as any)
const FeeScheduleRoute = FeeScheduleRouteImport.update({
  id: '/fee-schedule',
  path: '/fee-schedule',
  getParentRoute: () => rootRouteImport,
} as any)
const MeetTheFounderRoute = MeetTheFounderRouteImport.update({
  id: '/meet-the-founder',
  path: '/meet-the-founder',
  getParentRoute: () => rootRouteImport,
} as any)
const SolutionsRoute = SolutionsRouteImport.update({
  id: '/solutions',
  path: '/solutions',
  getParentRoute: () => rootRouteImport,
} as any)
const TheAcsApproachRoute = TheAcsApproachRouteImport.update({
  id: '/the-acs-approach',
  path: '/the-acs-approach',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/faqs': typeof FaqsRoute
  '/fee-schedule': typeof FeeScheduleRoute
  '/meet-the-founder': typeof MeetTheFounderRoute
  '/solutions': typeof SolutionsRoute
  '/the-acs-approach': typeof TheAcsApproachRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/faqs': typeof FaqsRoute
  '/fee-schedule': typeof FeeScheduleRoute
  '/meet-the-founder': typeof MeetTheFounderRoute
  '/solutions': typeof SolutionsRoute
  '/the-acs-approach': typeof TheAcsApproachRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/faqs': typeof FaqsRoute
  '/fee-schedule': typeof FeeScheduleRoute
  '/meet-the-founder': typeof MeetTheFounderRoute
  '/solutions': typeof SolutionsRoute
  '/the-acs-approach': typeof TheAcsApproachRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contact'
    | '/faqs'
    | '/fee-schedule'
    | '/meet-the-founder'
    | '/solutions'
    | '/the-acs-approach'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contact'
    | '/faqs'
    | '/fee-schedule'
    | '/meet-the-founder'
    | '/solutions'
    | '/the-acs-approach'
  id:
    | '__root__'
    | '/'
    | '/contact'
    | '/faqs'
    | '/fee-schedule'
    | '/meet-the-founder'
    | '/solutions'
    | '/the-acs-approach'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContactRoute: typeof ContactRoute
  FaqsRoute: typeof FaqsRoute
  FeeScheduleRoute: typeof FeeScheduleRoute
  MeetTheFounderRoute: typeof MeetTheFounderRoute
  SolutionsRoute: typeof SolutionsRoute
  TheAcsApproachRoute: typeof TheAcsApproachRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faqs': {
      id: '/faqs'
      path: '/faqs'
      fullPath: '/faqs'
      preLoaderRoute: typeof FaqsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fee-schedule': {
      id: '/fee-schedule'
      path: '/fee-schedule'
      fullPath: '/fee-schedule'
      preLoaderRoute: typeof FeeScheduleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meet-the-founder': {
      id: '/meet-the-founder'
      path: '/meet-the-founder'
      fullPath: '/meet-the-founder'
      preLoaderRoute: typeof MeetTheFounderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solutions': {
      id: '/solutions'
      path: '/solutions'
      fullPath: '/solutions'
      preLoaderRoute: typeof SolutionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/the-acs-approach': {
      id: '/the-acs-approach'
      path: '/the-acs-approach'
      fullPath: '/the-acs-approach'
      preLoaderRoute: typeof TheAcsApproachRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContactRoute: ContactRoute,
  FaqsRoute: FaqsRoute,
  FeeScheduleRoute: FeeScheduleRoute,
  MeetTheFounderRoute: MeetTheFounderRoute,
  SolutionsRoute: SolutionsRoute,
  TheAcsApproachRoute: TheAcsApproachRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
